spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: unSecretTresLongEtAleatoirePourSignerLesTokensJWT1234567890
  expiration: 900000